---

- name: Copy parameter.yml
  template:
    src=parameters.yml.j2
    dest="{{ symfony_parameters_path }}"
    owner=www-data
    group=www-data
    mode=0644

- name: Check vagrant parameters file existence
  stat: path=/var/www/{{ symfony_project_name }}/current/app/config/parameters.yml
  register: parameters_existence

- name: Copy symfony parameter file
  shell:
    cp /var/www/{{ symfony_project_name }}/shared/app/config/parameters.yml /var/www/{{ symfony_project_name }}/current/app/config/parameters.yml
  when: "'vagrant' in {{ group_names }} and not parameters_existence.stat.exists"
